const S={year:8,month:1,money:3200000,rep:42,day:0,training:'balanced',facilities:[],coaching:'strict',log:[],history:[['創設','小さな稽古場と、四人の弟子で部屋を開いた。']],selected:'arashi',relations:{arashi_hakuryu:-62,iwao_sora:44,arashi_iwao:24},rikishi:[
 {id:'arashi',name:'嵐山',rank:'幕下十五枚目',w:0,l:0,body:598,skill:510,mind:570,fatigue:12,mot:66,trust:61,color:'#315c8e',rival:'hakuryu'},
 {id:'hakuryu',name:'白龍',rank:'幕下十八枚目',w:0,l:0,body:546,skill:625,mind:475,fatigue:18,mot:71,trust:42,color:'#a9513e',rival:'arashi'},
 {id:'iwao',name:'岩尾',rank:'三段目六枚目',w:0,l:0,body:690,skill:430,mind:610,fatigue:9,mot:54,trust:73,color:'#6b8050',rival:null},
 {id:'sora',name:'蒼天',rank:'序二段四十枚目',w:0,l:0,body:460,skill:560,mind:520,fatigue:23,mot:48,trust:35,color:'#9a6eaf',rival:null}
]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>'¥'+n.toLocaleString('ja-JP');
function cliff(r){let left=15-S.day, need=Math.max(0,8-r.w);return need>left?'cliff':need===left?'warning':'safe'}
function phase(){return S.day<=5?['初日〜5日目','序盤戦 — 調子の揺れが勝敗を分ける。']:S.day<=10?['中日〜10日目','中盤戦 — 疲労と怪我の判断が、番付を左右する。']:['終盤〜千秋楽','終盤戦 — 優勝、昇進、そして崖っぷちの一番。']}
function render(){ $('#year').textContent=`令和${S.year}年`;$('#month').textContent=['一月場所','三月場所','五月場所','七月場所','九月場所','十一月場所'][S.month-1];$('#money').textContent=fmt(S.money);$('#reputation').textContent=S.rep;$('#repMeter').style.width=S.rep+'%';$('#rosterCount').textContent=S.rikishi.length+'人';let costs=210000+(S.facilities.includes('clinic')?90000:0);$('#balance').textContent='-'+fmt(costs);$('#day').textContent=S.day;let p=phase();$('#arcName').textContent=S.day? p[0]:'場所前';$('#arcText').textContent=p[1];$('#phaseLabel').textContent=S.day?'本場所 '+p[0]:'稽古期間';$('#tournamentTitle').textContent=$('#month').textContent;
 $('#rikishiCards').innerHTML=S.rikishi.map(r=>`<article class="rikishi ${S.selected===r.id?'focus':''}" data-select="${r.id}"><span class="rank">${r.rank}</span><h3>${r.name}</h3><div class="record">${r.w}勝 ${r.l}敗　疲労 ${r.fatigue}</div><div class="sprite" style="--sprite:${r.color}"></div><div class="statline"><span>心 ${r.mind}</span><span>技 ${r.skill}</span><span>体 ${r.body}</span></div>${cliff(r)!=='safe'?`<div class="cliff">${cliff(r)==='cliff'?'崖っぷち一番':'全勝必須ライン'}</div>`:`<div class="safe">安全圏まで あと ${Math.max(0,8-r.w)}勝</div>`}</article>`).join('');
 $('#tournamentRoster').innerHTML=S.rikishi.map(r=>`<div class="bout-row"><div><b>${r.name}</b> <span>${r.rank}</span></div><div class="mark">${r.w} - ${r.l}${cliff(r)==='cliff'?'　崖':''}</div></div>`).join('');
 $('#boutLog').innerHTML=S.log.length?S.log.slice(0,7).map(x=>`<div class="log-entry">${x}</div>`).join(''):'<p class="empty-log">取組の記録はここに表示されます。</p>';
 let sel=S.rikishi.find(x=>x.id===S.selected);$('#mentorCard').innerHTML=`<p class="label">師弟関係</p><h3>親方 × ${sel.name}</h3><p>信頼度 ${sel.trust}　/　指導方針：厳格　/　相性：${sel.trust>50?'良好':'緊張'}。信頼が低い弟子ほど、猛稽古で心が離れる。</p>`;
 let rel=(name,type,v,copy,color='var(--green)')=>`<article class="relation"><span class="tag" style="background:${color}">${type}</span><h3>${name}</h3><p>${copy}</p><div class="affinity"><i style="width:${Math.abs(v)}%;background:${v<0?'var(--red)':'var(--green)'}"></i></div></article>`;$('#relationList').innerHTML=rel('嵐山　×　白龍','犬猿の仲',S.relations.arashi_hakuryu,'同期入門。対戦時は互いに気迫補正が入る。','var(--red)')+rel('岩尾　×　蒼天','兄弟弟子',S.relations.iwao_sora,'稽古後、兄弟子の助言が蒼天の回復を助ける。')+rel('嵐山　×　岩尾','同郷',S.relations.arashi_iwao,'故郷からの便りが踏ん張りになる。','var(--gold)');
 $('#historyList').innerHTML=S.history.map(h=>`<div class="history-entry"><b>${h[0]}</b><p>${h[1]}</p></div>`).join('');$('#nextBout').textContent=S.day>=15?'場所を締める':'取組を開始する'; }
function modal(title,text,actions,label='DECISION'){ $('#modalLabel').textContent=label;$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modalActions').innerHTML='';actions.forEach(a=>{let b=document.createElement('button');b.textContent=a[0];b.onclick=()=>{$('#modal').classList.add('hidden');a[1]()};$('#modalActions').append(b)});$('#modal').classList.remove('hidden')}
function train(){let cfg={balanced:[6,4,0,'基礎鍛錬','全員の基礎能力を少しずつ伸ばす。厳しい番付では、焦りが怪我を呼ぶ。'],power:[13,14,10,'猛稽古','成長は大きいが、疲労の蓄積が怪我に直結する。'],recovery:[2,-12,-3,'調整稽古','場所を戦い抜くための温存策。番付を上げるには物足りない。']}[S.training];S.rikishi.forEach(r=>{let dojo=S.facilities.includes('dojo')?7:0, kitchen=S.facilities.includes('kitchen')?9:0;r.body+=cfg[0]+dojo+kitchen;r.skill+=cfg[0]+dojo;r.fatigue=Math.max(0,r.fatigue+cfg[1]-(S.facilities.includes('kitchen')?3:0)-(S.facilities.includes('clinic')?4:0));r.mot=Math.max(0,Math.min(100,r.mot-cfg[2]-(S.training==='power'&&r.trust<50?8:0)-(S.facilities.includes('dojo')&&r.trust<45?4:0)));});$('#trainingName').textContent=cfg[3];$('#trainingDesc').textContent=cfg[4]}
function advance(){if(S.day){modal('本場所の最中です','まずは十五日間を戦い抜いてください。',[['わかった',()=>{}]]);return}train();let costs=210000+(S.facilities.includes('clinic')?90000:0),income=90000+S.rep*1800;S.money+=income-costs;S.month++;if(S.month>6){S.month=1;S.year++}if(S.money<0){modal('部屋の閉鎖','資金が尽き、後援会も離れた。ここで土俵を降りる。',[['最初から',()=>location.reload()]],'GAME OVER');return}if(Math.random()<.27){let r=S.rikishi[Math.floor(Math.random()*4)];modal('稽古場での衝突',`${r.name}が厳しい稽古に反発している。信頼を取るか、規律を取るか。`,[['なだめる',()=>{r.trust+=10;r.mot+=4}],['押し通す',()=>{r.trust-=8;r.skill+=8}]],'RANDOM EVENT')}S.history.unshift([`${$('#month').textContent}を前に`, `月間収支 ${fmt(income-costs)}。稽古を積み、次の土俵へ向かう。`]);render()}
function bout(){if(S.day>=15){settle();return}S.day++;let ph=phase()[0];S.rikishi.forEach(r=>{let opp=500+Math.random()*190+(S.day>10?35:0), cliffNow=cliff(r), pressure=cliffNow==='cliff'?1.3:1, special=S.day>=11&&(r.w>=8||r.w===S.day-1), rivalry=(r.id==='arashi'||r.id==='hakuryu')?18:0, mindScale=(special?1.3:1)*(cliffNow==='cliff'?1.22:1), form=(r.body*.32+r.skill*.36+r.mind*.32*mindScale)+(r.mot-50)*3-r.fatigue*3+rivalry;let win=form+Math.random()*180*pressure>opp+Math.random()*180;if(win)r.w++;else r.l++;r.fatigue+=7+(S.training==='power'?4:0);let stake=(cliffNow==='cliff'?' <b>崖っぷち一番。</b>':'')+(special?' <b>終盤の大一番、館内が沸く。</b>':'');S.log.unshift(`<b>${S.day}日目・${ph}</b>　${r.name} ${win?'○':'●'}　${win?(special?'執念の寄り切りで勝利。':'押し出しで勝利。'): '土俵際で力尽きた。'}${stake}`);let injuryRate=.32+(S.facilities.includes('kitchen')?.10:0)-(S.facilities.includes('clinic')?.12:0);if(r.fatigue>68&&S.day>=6&&Math.random()<injuryRate)injuryChoice(r)});render()}
function injuryChoice(r){modal('強行出場か、休場か',`${r.name}の疲労は限界に近い。ここで無理をすれば長期離脱もあり得る。`,[['強行出場',()=>{r.mind+=14;r.fatigue+=15;S.log.unshift(`<b>決断</b>　${r.name}は痛みを抱え、土俵へ向かった。`)}],['休場',()=>{r.l+=2;r.fatigue=Math.max(0,r.fatigue-28);S.log.unshift(`<b>休場</b>　${r.name}は未来のため、土俵を離れた。`)}]],'INJURY DECISION')}
function settle(){let words=[];S.rikishi.forEach(r=>{if(r.w>=10){r.rank='十両昇進圏';S.money+=300000;S.rep+=5;words.push(`${r.name}が${r.w}勝。関取への道が開けた。`)}else if(r.w>=8){r.rank=r.rank.replace('十五','十').replace('十八','十二');words.push(`${r.name}は勝ち越し。番付を守った。`)}else if(r.w<=5){r.rank=r.rank.replace('幕下','三段目');r.mot=Math.max(0,r.mot-12);words.push(`${r.name}は負け越し。厳しい降格となる。`)}r.fatigue=Math.max(0,r.fatigue-24-(S.facilities.includes('clinic')?10:0));});let a=S.rikishi.find(r=>r.id==='arashi'),h=S.rikishi.find(r=>r.id==='hakuryu');if(a.w!==h.w)S.relations.arashi_hakuryu=Math.max(-100,S.relations.arashi_hakuryu-5);S.history.unshift([`${$('#month').textContent} 千秋楽`,words.join(' ')]);modal('場所を終えて',words.join('\n'),[['次の稽古へ',()=>{S.day=0;S.log=[];S.rikishi.forEach(r=>{r.w=0;r.l=0});render()}]],'BASHO RESULT')}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#advanceMonth').onclick=advance;$('#nextBout').onclick=bout;$('#rikishiCards').onclick=e=>{let c=e.target.closest('[data-select]');if(c){S.selected=c.dataset.select;render()}};$('#trainingChoices').onclick=e=>{let b=e.target.closest('[data-train]');if(!b)return;S.training=b.dataset.train;$$('#trainingChoices button').forEach(x=>x.classList.toggle('chosen',x===b));let n={balanced:['基礎鍛錬','全員の基礎能力を少しずつ伸ばす。厳しい番付では、焦りが怪我を呼ぶ。'],power:['猛稽古','成長は大きいが、疲労の蓄積が怪我に直結する。'],recovery:['調整稽古','場所を戦い抜くための温存策。番付を上げるには物足りない。']}[S.training];$('#trainingName').textContent=n[0];$('#trainingDesc').textContent=n[1]};$$('[data-facility]').forEach(b=>b.onclick=()=>{let type=b.dataset.facility,cost={kitchen:850000,dojo:1200000,clinic:1500000}[type];if(S.facilities.includes(type))return modal('すでに導入済み','この設備は稼働しています。',[['閉じる',()=>{}]]);if(S.money<cost)return modal('資金不足','部屋の財布に余裕がない。投資は先送りするしかない。',[['閉じる',()=>{}]]);S.money-=cost;S.facilities.push(type);if(type==='kitchen')S.rikishi.forEach(r=>r.body+=30);if(type==='dojo')S.rikishi.forEach(r=>r.skill+=28);S.history.unshift(['設備投資',b.querySelector('b').textContent+'を導入した。恩恵と代償は、これから現れる。']);render()});render();
