(()=>{
  const $=s=>document.querySelector(s),acts=['四股','ぶつかり','技術','休養'],days=['月','火','水','木','金','土','日'];
  let V='home';
  const state=()=>{let z=S.pennant;if(!z){z=S.pennant={ready:false,phase:'create',prep:1,day:0,w:0,l:0,policy:'基礎重視',schedule:['四股','ぶつかり','休養','技術','四股','ぶつかり','休養'],recent:[],news:['春風部屋、最初の弟子を迎える。'],career:{bouts:0,w:0,l:0,streak:0,best:0,kimarite:{寄り切り:0,押し出し:0}}}}return z};
  const man=()=>S.rikishi[0];
  const bg=n=>`<img class="scene-bg" src="assets/retro/${n}" aria-hidden="true">`;
  const sprite=()=>`<i class="solo-sprite v${man().avatar?.variant||0}"></i>`;
  const form=()=>{let x=man();return `<div class="pen-form"><span>体調 <b style="width:${100-x.fatigue}%"></b></span><span>気力 <b class="yellow" style="width:${x.mot}%"></b></span><span>疲労 <b class="red" style="width:${x.fatigue}%"></b></span></div>`};
  const home=()=>{let z=state(),x=man(),next=z.phase==='basho'?'本場所 初日':z.schedule[(z.prep-1)%7];return `<section class="pg-scene pen-home">${bg('dojo-hall.png')}<div class="pen-top"><b>令和${S.year}年　一月場所</b><span>${z.phase==='basho'?'本場所開催中':`本場所まで あと ${13-z.prep}日`}</span></div><div class="pen-hero">${sprite()}<div><h2>${x.name}</h2><p>${x.rank}　${z.phase==='basho'?`${z.w}勝 ${z.l}敗`:'新弟子・横綱を目指す'}</p>${form()}</div></div><div class="pen-result"><article><b>次の予定</b><strong>${next}</strong><small>${z.phase==='basho'?'一日ずつ、結果を見届けよう。':'方針と予定はいつでも変えられる。'}</small></article><article><b>直近6番</b><strong>${z.recent.length?z.recent.slice(0,6).map(v=>v?'○':'●').join('　'):'—'}</strong><small>通算 ${z.career.w}勝 ${z.career.l}敗</small></article><article><b>主な出来事</b><small>${z.news[0]}</small></article></div><div class="pen-news"><b>番付ニュース</b>${z.news.slice(0,3).map(n=>`<span>・${n}</span>`).join('')}</div></section>`};
  const schedule=()=>{let z=state();return `<section class="pg-scene pen-schedule">${bg('dojo-hall.png')}<header><b>今日の部屋方針</b><span>基本は一括設定。気になる日だけ変える。</span></header><div class="pen-policy">${['基礎重視','攻め重視','技術重視','回復重視'].map(v=>`<button data-pol="${v}" class="${z.policy===v?'on':''}">${v}<small>${{基礎重視:'足腰を作る',攻め重視:'押しを磨く',技術重視:'技を覚える',回復重視:'疲労を抜く'}[v]}</small></button>`).join('')}</div><h3>今週の予定</h3><div class="pen-week">${z.schedule.map((v,i)=>`<button data-plan="${i}" class="${i===((z.prep-1)%7)?'today':''}"><i>${v==='四股'?'♨':v==='ぶつかり'?'✦':v==='技術'?'◇':'☾'}</i><b>${days[i]}</b><span>${v}</span></button>`).join('')}</div><p>「おまかせ」の予定を土台に、疲れている日だけ休養へ替えよう。</p></section>`};
  const profile=()=>{let z=state(),x=man(),c=x.caps||{body:720,skill:720,mind:720};return `<section class="pg-scene pen-profile">${bg('dojo-hall.png')}<div class="pen-card">${sprite()}<div><h2>${x.name}</h2><p>${x.rank}　得意：${x.specialty||'基礎'}</p>${form()}<div class="pen-abilities"><span>押し <b>${Math.round(x.body/10)}</b> / ${Math.round(c.body/10)}</span><span>技 <b>${Math.round(x.skill/10)}</b> / ${Math.round(c.skill/10)}</span><span>心 <b>${Math.round(x.mind/10)}</b> / ${Math.round(c.mind/10)}</span></div></div></div><div class="pen-record"><h3>通算成績</h3><b>${z.career.w}勝 ${z.career.l}敗</b><span>連勝 ${z.career.best}</span><span>寄り切り ${z.career.kimarite.寄り切り}</span><span>押し出し ${z.career.kimarite.押し出し}</span><p>年度別成長：新弟子として、最初の場所に挑む。</p></div></section>`};
  const basho=()=>{let z=state(),d=z.day+1,focus=[1,7,8,15].includes(d),table=[['1','雷ノ海','7-'+Math.max(0,d-1)],['2','北海山','6-'+Math.max(0,d-2)],['3',man().name,`${z.w}-${z.l}`],['4','大翔嵐','5-'+Math.max(0,d-3)],['5','若武者','5-'+Math.max(0,d-4)]];return `<section class="pg-scene pen-basho">${bg('basho-arena.png')}<div class="pen-score"><b>${d}日目　${man().name} ${z.w}勝${z.l}敗</b><span>次の相手：${d%3?'北海山':'大翔嵐'}</span></div><img class="bout-duo" src="assets/bout-duo-v1.png"><div class="pen-bout-report"><b>${focus?'注目の一番':'本日の取組'}</b><span>${focus?'勝ち越しへ、ここが大事な土俵。':'結果はオートで進行します。'}</span></div><div class="pen-standings"><b>幕下・優勝争い</b>${table.map(v=>`<span>${v[0]}　${v[1]} <strong>${v[2]}</strong></span>`).join('')}</div><button class="pen-three" data-sim="3">▶ 3日まとめて進める</button></section>`};
  const history=()=>`<section class="pg-scene history-scene">${bg('dojo-hall.png')}<h2>場所のニュース・記録</h2><div>${state().news.slice(0,8).map((n,i)=>`<article><b>${i===0?'最新':'番付ニュース'}</b><p>${n}</p></article>`).join('')}</div></section>`;
  function render(){let z=state(),screen=!z.ready?setup():V==='schedule'?schedule():V==='profile'?profile():V==='basho'?basho():V==='history'?history():home();$('#pgViewport').innerHTML=screen;$('#pgDialogue').textContent=!z.ready?'一人の弟子を横綱へ導こう。':z.news[0];$('#pgPrimary').textContent=!z.ready?'弟子を迎える':V==='schedule'?'予定を決定':V==='basho'?(z.day>=15?'場所を締める':'▶ 1日進める'):z.phase==='basho'?'▶ 本場所へ':'▶ 今日を進める';document.querySelectorAll('[data-pg-view]').forEach(b=>b.querySelector('span').textContent=({dojo:'ホーム',facility:'経営',profile:'成績',scout:'予定',basho:'本場所',history:'記録'})[b.dataset.pgView]);bind()}
  function setup(){return `<section class="pg-scene create-scene">${bg('dojo-hall.png')}<div class="create-card"><p>NEW DESHI</p><h2>最初の弟子を迎える</h2>${sprite()}<input id="penName" value="${man().name||'虎丸'}" maxlength="8"><div class="look-buttons"><button data-look="face">顔</button><button data-look="body">体型</button><button data-look="mawashi">まわし</button></div><small>最初は一人だけ。記録と番付を積み上げ、横綱を目指す。</small></div></section>`}
  function advance(n=1){let z=state(),x=man();for(let i=0;i<n&&z.day<15;i++){let d=z.day+1,opp=555+d*7+(d>10?28:0),score=x.body*.34+x.skill*.34+x.mind*.32+x.mot*2-x.fatigue*2.1+(Math.random()-.5)*130,win=score>opp,kim=win?(x.body>x.skill?'押し出し':'寄り切り'):null;z.day++;z.career.bouts++;if(win){z.w++;z.career.w++;z.career.streak++;z.career.best=Math.max(z.career.best,z.career.streak);z.career.kimarite[kim]++;z.news.unshift(`${d}日目、${x.name}は${kim}で白星。${z.w}勝${z.l}敗。`)}else{z.l++;z.career.l++;z.career.streak=0;z.news.unshift(`${d}日目、${x.name}は黒星。次の土俵で取り返したい。`)}z.recent.unshift(win);x.fatigue=Math.min(100,x.fatigue+5);x.mot=Math.max(0,Math.min(100,x.mot+(win?4:-3)))}if(z.day===15){let ok=z.w>=8;z.news.unshift(`一月場所を${z.w}勝${z.l}敗で終えた。${ok?'勝ち越し、番付上昇が見込まれる！':'悔しい負け越し。稽古を見直そう。'}`);if(ok){x.rank=x.rank==='新弟子'?'序ノ口':'序二段';S.rep+=4;S.money+=180000}}}
  function train(){let z=state(),x=man(),a=z.schedule[(z.prep-1)%7];if(a==='四股'){x.body+=2;x.mind+=1;x.fatigue+=3}else if(a==='ぶつかり'){x.body+=4;x.skill+=1;x.fatigue+=7}else if(a==='技術'){x.skill+=4;x.mind+=1;x.fatigue+=4}else{x.fatigue=Math.max(0,x.fatigue-11);x.mot=Math.min(100,x.mot+5)}z.news.unshift(`${z.prep}日目：${a}。${x.name}は少しずつ力をつけている。`);z.prep++;if(z.prep>12){z.phase='basho';z.news.unshift('稽古期間を終え、本場所が始まる。')}V='home'}
  function bind(){let z=state();document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>{let x=man();x.avatar??={face:0,body:0,mawashi:0,variant:0};x.avatar[b.dataset.look]=(x.avatar[b.dataset.look]+1)%4;x.avatar.variant=(x.avatar.face+x.avatar.body+x.avatar.mawashi)%4;render()});document.querySelectorAll('[data-pol]').forEach(b=>b.onclick=()=>{z.policy=b.dataset.pol;let p={基礎重視:'四股',攻め重視:'ぶつかり',技術重視:'技術',回復重視:'休養'}[z.policy];z.schedule=z.schedule.map((_,i)=>i===6?'休養':p);render()});document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{let i=+b.dataset.plan;z.schedule[i]=acts[(acts.indexOf(z.schedule[i])+1)%acts.length];render()});document.querySelectorAll('[data-sim]').forEach(b=>b.onclick=()=>{advance(+b.dataset.sim);render()})}
  document.querySelectorAll('[data-pg-view]').forEach(b=>b.onclick=()=>{V=b.dataset.pgView==='dojo'?'home':b.dataset.pgView==='scout'?'schedule':b.dataset.pgView==='facility'?'home':b.dataset.pgView;render()});$('#pgPrimary').onclick=()=>{let z=state(),x=man();if(!z.ready){x.name=$('#penName').value.trim()||'虎丸';x.rank='新弟子';x.body=x.skill=x.mind=430;x.fatigue=8;x.mot=65;x.specialty='基礎';x.caps={body:720,skill:720,mind:720};S.rikishi=[x];z.ready=true;z.phase='prep';z.news.unshift(`${x.name}が春風部屋へ入門。横綱への物語が始まる。`)}else if(V==='schedule')V='home';else if(V==='basho'){if(z.day>=15){z.phase='prep';z.prep=1;z.day=z.w=z.l=0;z.recent=[];V='home';z.news.unshift('次の場所へ向け、稽古を再開した。')}else advance()}else if(z.phase==='basho')V='basho';else train();render()};render()
})();
