(() => {
  const P={view:'dojo',dojoPhase:'stable'},$=s=>document.querySelector(s),fmt=n=>'¥'+n.toLocaleString('ja-JP');
  const dude=(r,cl='')=>`<i class="pg-dude ${cl}" style="--c:${r.color}"><b>${r.name}</b></i>`;
  const bg=name=>`<img class="scene-bg" src="assets/retro/${name}" aria-hidden="true">`;
  const practice={shiko:{name:'四股',kind:'balanced',image:'training-shiko-v1.png',motion:'shiko',note:'耐久を鍛える。疲労は少なめ。'},teppo:{name:'鉄砲',kind:'power',image:'training-duo-v1.png',motion:'push',note:'筋力を鍛える。疲労がたまる。'},moushi:{name:'組み稽古',kind:'power',image:'training-duo-v1.png',motion:'push',note:'技と気迫を鍛える。'},chanko:{name:'ちゃんこ',kind:'recovery',image:'training-rest-v1.png',motion:'rest',note:'体づくりと気力を回復。'},rest:{name:'休養',kind:'recovery',image:'training-rest-v1.png',motion:'rest',note:'疲労を抜いて次に備える。'}};
  const plans={push:['押し重視','筋力↑　疲労↑','push'],basic:['基礎','全能力を少しずつ','shiko'],adjust:['調整','疲労↓　技を確認','shiko'],rest:['休養','疲労↓↓　気力↑','rest']};
  function dojoScene(){const avg=Math.round(S.rikishi.reduce((a,r)=>a+r.mot,0)/S.rikishi.length),fat=Math.round(S.rikishi.reduce((a,r)=>a+r.fatigue,0)/S.rikishi.length),active=Object.values(S.instructions||{}).includes('push')?practice.teppo:Object.values(S.instructions||{}).includes('rest')?practice.chanko:practice.shiko,ready=P.dojoPhase==='ready';return `<section class="pg-scene dojo-scene">${bg('dojo-hall.png')}<img class="training-duo ${active.motion}" src="assets/${active.image}" aria-label="${active.name}"><i class="training-label">${active.name}　${ready?'今日の指示を実行準備':'今日も稽古を始めよう'}</i><i class="dojo-sign">${ready?'指示済':'稽古場'}</i><i class="gain a">${ready?S.practiceNote:'下の「指示」から稽古内容を決めよう'}</i><aside class="pg-panel"><b>部屋の状態</b><small>気力：${avg}<br>疲労：${fat}<br>本場所まで：${7-(S.practiceDay||1)}日</small></aside><strong class="scene-caption">春風部屋　${ready?'稽古準備完了':'稽古場'}</strong></section>`}
  function dojoOrders(){const today=Math.min(6,S.practiceDay||1),week=['月','火','水','木','金','土'];S.instructions??={};return `<section class="pg-scene command-scene">${bg('dojo-hall.png')}<div class="command-head"><div class="practice-schedule">${week.map((d,i)=>`<i class="${i+1===today?'today':i+1<today?'done':''}">${d}<b>${i+1===today?'今日':i+1<today?'済':''}</b></i>`).join('')}</div><b>今日の稽古方針：<em>個別指示</em></b><span>本場所まで あと ${7-today}日</span></div><div class="command-tools"><button data-all-plan="basic">全員 基礎</button><button data-all-plan="rest">疲労者を休養</button></div><div class="instruction-list">${S.rikishi.map((r,i)=>{const p=S.instructions[r.id]||'basic',v=r.avatar?.variant??i,near=r.body>=cap(r,'body')*.9||r.skill>=cap(r,'skill')*.9;return `<article><i class="plan-face v${v}"></i><div><b>${r.name}</b><small>${r.rank}　得意：${r.specialty||'基礎'}</small></div><div class="condition ${r.fatigue>55?'tired':'good'}">${r.fatigue>55?'疲労':near?'限界付近':'好調'}<small>気力 ${r.mot}　疲労 ${r.fatigue}</small></div><div class="mini-stats"><span>押 ${Math.round(r.body/10)}/${Math.round(cap(r,'body')/10)}</span><span>技 ${Math.round(r.skill/10)}/${Math.round(cap(r,'skill')/10)}</span><span>心 ${Math.round(r.mind/10)}/${Math.round(cap(r,'mind')/10)}</span></div><button data-plan="${r.id}" class="plan-${p}">${plans[p][0]}<small>${plans[p][1]}</small></button></article>`}).join('')}</div><div class="command-memo">親方メモ：得意な稽古は伸びやすい。能力が上限の9割を超えると成長は鈍るが、好調・稽古場で少し伸ばしやすい。</div></section>`}
  function dojo(){return P.dojoPhase==='orders'?dojoOrders():dojoScene()}
  function facility(){const support=S.support??28,food=S.food??64,staff=S.staff??1;return `<section class="pg-scene facility-scene">${bg('dojo-hall.png')}<h2>部屋経営・施設購入</h2><div class="finance-strip"><span>後援会 <b>${support}</b></span><span>食材 <b>${food}</b></span><span>人員 <b>${staff}人</b></span><span>月固定費 <b>¥${(165000+staff*45000).toLocaleString()}</b></span></div><div class="fac-grid">${[['kitchen','ちゃんこ場','♨'],['dojo','稽古場','◯'],['clinic','医務室','✚']].map(x=>`<button data-fac2="${x[0]}"><i>${x[2]}</i><b>${x[1]}</b><span>${S.facilities.includes(x[0])?'導入済み':'購入する'}</span></button>`).join('')}</div><div class="finance-actions"><button data-finance="food">食材を仕入れる<br><small>¥80,000　食材 +35</small></button><button data-finance="staff">世話人を雇う<br><small>¥300,000　人員 +1 / 固定費増</small></button></div><p class="finance-note">後援会は場所後の収入、食材は稽古効率、人員は回復と固定費に影響。</p></section>`}
  function basho(){let r=S.rikishi.find(x=>x.id===S.loop?.focusId)||S.rikishi[0];return `<section class="pg-scene basho-scene">${bg('basho-arena.png')}<div class="bout east"><b>東　${r.name}</b><span>耐久 ${r.body}</span><span>技 ${r.skill}</span></div><div class="bout west"><b>西　大翔嵐</b><span>耐久 620</span><span>技 610</span></div><img class="bout-duo" src="assets/bout-duo-v1.png" aria-label="取組中"><strong class="scene-caption">${S.day?`${S.day}日目　${r.w}勝 ${r.l}敗`:'場所前　取組を待つ'}</strong></section>`}
  function history(){return `<section class="pg-scene history-scene">${bg('dojo-hall.png')}<h2>相撲博物館・部屋の歴史</h2><div>${S.history.slice(0,6).map(h=>`<article><b>${h[0]}</b><p>${h[1]}</p></article>`).join('')}</div></section>`}
  function practiceToday(){S.food??=64;const chosen=Object.values(S.instructions||{});S.training=chosen.includes('push')?'power':chosen.length&&chosen.every(x=>x==='rest')?'recovery':'balanced';let note=[];S.rikishi.forEach(r=>{const p=(S.instructions||{})[r.id]||'basic';if(p==='push'){const up=grow(r,'body',5,'押し'),tech=grow(r,'skill',2,'押し');r.fatigue+=7;r.mot=Math.max(0,r.mot-1);note.push(`${r.name} 押+${up} 技+${tech}`)}else if(p==='adjust'){const up=grow(r,'skill',2,'調整');r.fatigue=Math.max(0,r.fatigue-4);note.push(`${r.name} 技+${up}・疲労-4`)}else if(p==='rest'){r.fatigue=Math.max(0,r.fatigue-11);r.mot=Math.min(100,r.mot+4);note.push(`${r.name} 回復`)}else{const up=grow(r,'body',2,'基礎'),tech=grow(r,'skill',2,'基礎');r.fatigue+=3;note.push(`${r.name} 押+${up} 技+${tech}`)} });S.practiceNote=note.join('　');S.practiceDay=(S.practiceDay||1)+1;S.practiceCount=(S.practiceCount||0)+1;P.dojoPhase='stable';draw();}
  function draw(){let v=P.view==='dojo'?dojo():P.view==='facility'?facility():P.view==='basho'?basho():history();$('#pgViewport').innerHTML=v;$('#pgMoney').textContent=fmt(S.money);$('#pgRep').textContent=S.rep;document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{const id=b.dataset.plan,current=(S.instructions||{})[id]||'basic',keys=Object.keys(plans);S.instructions??={};S.instructions[id]=keys[(keys.indexOf(current)+1)%keys.length];draw()});document.querySelectorAll('[data-all-plan]').forEach(b=>b.onclick=()=>{S.instructions??={};S.rikishi.forEach(r=>{S.instructions[r.id]=b.dataset.allPlan==='rest'&&r.fatigue>35?'rest':'basic'});draw()});document.querySelectorAll('[data-finance]').forEach(b=>b.onclick=()=>{if(b.dataset.finance==='food'&&S.money>=80000){S.money-=80000;S.food=Math.min(100,(S.food??64)+35)}if(b.dataset.finance==='staff'&&S.money>=300000){S.money-=300000;S.staff=(S.staff??1)+1}draw()});document.querySelectorAll('[data-fac2]').forEach(b=>b.onclick=()=>{document.querySelector(`[data-facility="${b.dataset.fac2}"]`)?.click();setTimeout(draw,0)});$('#pgPrimary').textContent=P.view==='basho'?(S.day>=15?'場所結果を見る':'▶ 1日進行'):(P.view==='dojo'&&S.practiceDay>6?'▶ 本場所へ':P.dojoPhase==='orders'?'✓ 指示を決定':P.dojoPhase==='ready'?'▶ 今日の稽古を実行':'⚑ 指示を出す');const mobile=$('#mobileAdvance');if(mobile)mobile.textContent=P.view==='dojo'&&P.dojoPhase==='stable'?'指示':'進行'}
  document.querySelectorAll('[data-pg-view]').forEach(b=>b.onclick=()=>{let v=b.dataset.pgView;if(v==='profile')return $('#openProfile').click();if(v==='scout')return $('#scoutButton').click();P.view=v;P.dojoPhase='stable';draw()});$('#pgPrimary').onclick=()=>{if(P.view==='dojo'){if(S.practiceDay>6){P.view='basho';$('#advanceMonth').click()}else if(P.dojoPhase==='stable'){P.dojoPhase='orders';draw()}else if(P.dojoPhase==='orders'){P.dojoPhase='ready';draw()}else practiceToday()}else if(P.view==='basho')$('#nextBout').click();setTimeout(draw,0)};document.addEventListener('click',()=>setTimeout(draw,0));draw();
})();
