(() => {
  const P={view:'dojo'},$=s=>document.querySelector(s),fmt=n=>'¥'+n.toLocaleString('ja-JP');
  const dude=(r,cl='')=>`<i class="pg-dude ${cl}" style="--c:${r.color}"><b>${r.name}</b></i>`;
  const bg=name=>`<img class="scene-bg" src="assets/retro/${name}" aria-hidden="true">`;
  function dojo(){return `<section class="pg-scene dojo-scene">${bg('dojo-hall.png')}${S.rikishi.slice(0,4).map((r,i)=>dude(r,'d'+i)).join('')}<i class="dojo-sign">稽古中</i><i class="gain a">筋力 +3<br>技巧 +2</i><i class="gain b">耐久 +2</i><aside class="pg-panel"><b>稽古方針</b>${[['power','集中'],['balanced','普通'],['recovery','休養']].map(x=>`<button data-train2="${x[0]}" class="${S.training===x[0]?'on':''}">${x[1]}</button>`).join('')}<small>モチベーション：${Math.round(S.rikishi.reduce((a,r)=>a+r.mot,0)/S.rikishi.length)}</small></aside><strong class="scene-caption">春風部屋　稽古中</strong></section>`}
  function facility(){return `<section class="pg-scene facility-scene">${bg('dojo-hall.png')}<h2>施設購入</h2><div class="fac-grid">${[['kitchen','ちゃんこ場','♨'],['dojo','稽古場','◯'],['clinic','医務室','✚']].map(x=>`<button data-fac2="${x[0]}"><i>${x[2]}</i><b>${x[1]}</b><span>${S.facilities.includes(x[0])?'導入済み':'購入する'}</span></button>`).join('')}</div></section>`}
  function basho(){let r=S.rikishi.find(x=>x.id===S.loop?.focusId)||S.rikishi[0];return `<section class="pg-scene basho-scene">${bg('basho-arena.png')}<div class="bout east"><b>東　${r.name}</b><span>耐久 ${r.body}</span><span>技 ${r.skill}</span></div><div class="bout west"><b>西　大翔嵐</b><span>耐久 620</span><span>技 610</span></div>${dude(r,'fight left')}<i class="pg-dude fight right"><b>大翔嵐</b></i><strong class="scene-caption">${S.day?`${S.day}日目　${r.w}勝 ${r.l}敗`:'場所前　取組を待つ'}</strong></section>`}
  function history(){return `<section class="pg-scene history-scene">${bg('dojo-hall.png')}<h2>相撲博物館・部屋の歴史</h2><div>${S.history.slice(0,6).map(h=>`<article><b>${h[0]}</b><p>${h[1]}</p></article>`).join('')}</div></section>`}
  function draw(){let v=P.view==='dojo'?dojo():P.view==='facility'?facility():P.view==='basho'?basho():history();$('#pgViewport').innerHTML=v;$('#pgMoney').textContent=fmt(S.money);$('#pgRep').textContent=S.rep;document.querySelectorAll('[data-train2]').forEach(b=>b.onclick=()=>{document.querySelector(`[data-train="${b.dataset.train2}"]`)?.click();draw()});document.querySelectorAll('[data-fac2]').forEach(b=>b.onclick=()=>{document.querySelector(`[data-facility="${b.dataset.fac2}"]`)?.click();setTimeout(draw,0)});$('#pgPrimary').textContent=P.view==='basho'?(S.day>=15?'場所結果を見る':'▶ 5日進行'):'場所前ミーティング'}
  document.querySelectorAll('[data-pg-view]').forEach(b=>b.onclick=()=>{let v=b.dataset.pgView;if(v==='profile')return $('#openProfile').click();if(v==='scout')return $('#scoutButton').click();P.view=v;draw()});$('#pgPrimary').onclick=()=>{(P.view==='basho'?$('#quickBout'):$('#advanceMonth')).click();setTimeout(draw,0)};document.addEventListener('click',()=>setTimeout(draw,0));draw();
})();
