(() => {
  const screen=document.querySelector('#profileScreen'), roster=document.querySelector('#profileRoster');
  const data=r=>({style:r.skill>r.body?'技巧派':'押し相撲',potential:r.skill+r.body+r.mind>1750?'B':'C',trait:r.trust<45?'気難しいが勝負師':r.mind>580?'土俵度胸あり':'素直な努力家'});
  const pos=['0%','33.333%','66.667%','100%'], colors=['#315c8e','#a9513e','#6b8050','#9a6eaf'];
  function show(r){S.selected=r.id;r.avatar??={face:0,body:0,mawashi:0,variant:0};roster.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.id===r.id));const d=data(r),portrait=document.querySelector('#profilePortrait'),c=r.caps||{body:760,skill:760,mind:760};portrait.style.setProperty('--sprite',r.color);portrait.style.backgroundImage="url('assets/rikishi-sprites-v2.png')";portrait.style.backgroundSize='auto 92%';portrait.style.backgroundPosition=`${pos[r.avatar.variant]} 4px`;portrait.style.backgroundRepeat='no-repeat';portrait.innerHTML=`<b>${r.name}</b><span>${r.rank}</span>`;document.querySelector('#profileStats').innerHTML=`<p>相撲型：<b>${d.style}</b>　得意稽古：<b>${r.specialty||'基礎'}</b></p><p>潜在能力：<b>${d.potential}</b></p><p>成長目安：押 <b>${r.body}/${c.body}</b>　技 <b>${r.skill}/${c.skill}</b>　心 <b>${r.mind}/${c.mind}</b></p><p>信頼度：<b>${r.trust}</b>　疲労：<b>${r.fatigue}</b></p><div class="avatar-edit"><b>見た目エディット</b><button data-look="face">顔</button><button data-look="body">体型</button><button data-look="mawashi">廻し</button></div>`;const vals=[r.mind,r.skill,r.body,Math.max(0,100-r.fatigue)*7,Math.min(700,r.mot*7)].map(n=>Math.min(100,Math.round(n/7)));document.querySelector('#profileRadar').innerHTML=`<i style="--a:${vals[0]}%;--b:${vals[1]}%;--c:${vals[2]}%;--d:${vals[3]}%;--e:${vals[4]}%"></i><span>心</span><span>技</span><span>体</span><span>回復</span><span>気力</span>`;document.querySelector('#profileMessage').textContent=`親方の所感：「${r.name}は、${d.trait}。得意な稽古を生かし、限界の先を狙え。」`;}
  function open(){roster.innerHTML=S.rikishi.map(r=>`<button data-id="${r.id}"><i style="--sprite:${r.color}"></i><b>${r.name}</b><span>${r.rank}</span></button>`).join('');roster.querySelectorAll('button').forEach(b=>b.onclick=()=>show(S.rikishi.find(r=>r.id===b.dataset.id)));show(S.rikishi.find(r=>r.id===S.selected)||S.rikishi[0]);screen.classList.remove('hidden');}
  document.querySelector('#openProfile').onclick=open;document.querySelector('#closeProfile').onclick=()=>screen.classList.add('hidden');
  document.querySelector('#profileStats').onclick=e=>{const b=e.target.closest('[data-look]');if(!b)return;const r=S.rikishi.find(x=>x.id===S.selected);r.avatar??={face:0,body:0,mawashi:0,variant:0};r.avatar[b.dataset.look]=(r.avatar[b.dataset.look]+1)%4;r.avatar.variant=(r.avatar.face+r.avatar.body+r.avatar.mawashi)%4;r.color=colors[r.avatar.mawashi];show(r);document.querySelector('.dojo-scene .retro-team')?.remove();};
})();
